version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - dnc-net
      
backend:
  image: rhythmbear/dnc
  restart: always
  ports:
    - "5000:5000"
  networks:
    - dnc-net
  depends_on:
    - redis
    - db
  command: gunicorn -b :5000 --access-logfile - dnc:app

worker:
  image: rhythmbear/dnc
  restart: always
  command: celery -A dnc.celery worker --uid=1
  networks:
    - dnc-net
  depends_on:
    - redis
    - db

db:
  image: mysql:8.0
  restart: always
  environment:
    MYSQL_DATABASE: 'db'
    MYSQL_USER: 'user'
    MYSQL_PASSWORD: 'password'
    MYSQL_ROOT_PASSWORD: 'password'
  networks:
    - dnc-net
  ports:
    - '3306:3306'
  volumes:
    - /var/lib/mysql:/var/lib/mysql
networks:
  dnc-net: