name: Create Pull request

on:
  push:
    branches:
      - PW-local

    jobs:
      create-pull-request:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v2
          
          - name: Get Commit Message
            id: commit_message
            run: echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

          - name: Create Pull Request
            if: contains(env.commit_message, 'DeployPR')
            uses: peter-evans/create-pull-request@v5
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              commit-message: Automated pull request
              title: Automated pull request
              body: Pull Request to merge code into main for production
              branch: main
              base: PW-local