name: Deploy to Heroku

on:
  push:
    branches: main

# Defining Workflow
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Repository.
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        
    - name: Set Heroku stack to container
      run: |
        heroku stack:set container --app ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}


    # This is where i build and push the docker image to heroku
    - name: Build, Push and release a docker container to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
      # Defining all the secrets and ensure that they are set in the Github repository
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_directory: ./
        dockerfile_name: Dockerfile
        docker_options: "--build-arg SECRET_KEY=${{ secrets.SECRET_KEY }}"
          # --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
          # --build-arg MY_USERNAME=${{ secrets.MY_USERNAME }} \
          # --build-arg MY_PASSWORD=${{ secrets.MY_PASSWORD }} \
          # --build-arg PROD_DB_HOST=${{ secrets.PROD_DB_HOST }} \
          # --build-arg PROD_DB_USER=${{ secrets.PROD_DB_USER }} \
          # --build-arg PROD_DB_PW=${{ secrets.PROD_DB_PW }} \
          # --build-arg PROD_DB_NAME=${{ secrets.PROD_DB_NAME }} .

        process_type: web
